

words = [
        "Competitive",
        "Thrilling",
        "Exciting",
        "Dynamic",
        "High-scoring",
        "Fast-paced",
        "Elite",
        "Entertaining",
        "Prestigious",
        "Professional",
        "Popular",
        "Global",
        "Diverse",
        "Talented",
        "Intense",
        "Fierce",
        "Passionate",
        "Iconic",
        "Historic",
        "Progressive",
        "Electric",
        "Unpredictable",
        "Well-organized",
        "Engaging",
        "Celebrated",
        "Impactful",
        "Respected",
        "Innovative",
        "Fanatical",
        "Iconic"
    ]
