league_words = [
        "Competitive",
        "Thrilling",
        "Exciting",
        "Dynamic",
        "High-scoring",
        "Fast-paced",
        "Elite",
        "Entertaining",
        "Prestigious",
        "Professional",
        "Popular",
        "Global",
        "Diverse",
        "Talented",
        "Intense",
        "Fierce",
        "Passionate",
        "Iconic",
        "Historic",
        "Progressive",
        "Electric",
        "Unpredictable",
        "Well-organized",
        "Engaging",
        "Celebrated",
        "Impactful",
        "Respected",
        "Innovative",
        "Fanatical",
        "Iconic"
    ]

team_words = [
    "Dominant", "Majestic", "Unstoppable", "Powerful", "Spectacular",
    "Extraordinary", "Mythical", "Unpredictable", "Talented", "Versatile",
    "Creative", "Tenacious", "Unbreakable", "Fearless", "Explosive",
    "Flawless", "Resilient", "Unrivaled", "Phenomenal", "Exciting",
    "Mesmerizing", "Unmatched", "Unconquerable", "Innovative", "Dauntless",
    "Agile", "Charismatic", "Unforgettable", "Electric", "Unfathomable",
    "Inspirational", "Enigmatic", "Magical", "Ruthless", "Formidable",
    "Brilliant", "Versatile", "Awe-inspiring", "Supernatural", "Unyielding",
    "Pioneering", "Unbelievable", "Ruthless", "Unorthodox", 
]
